[build]
builder = "NIXPACKS"
watchPatterns = ["backend/**", "frontend/**"]

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 300

[[services]]
name = "backend"
source = "backend"

[services.build]
buildCommand = "npm install"

[services.deploy]
startCommand = "npm start"
healthcheckPath = "/health"

[[services]]
name = "frontend"
source = "frontend"

[services.build]
buildCommand = "npm install && npm run build"

[services.deploy]
startCommand = "npm run preview -- --host 0.0.0.0 --port $PORT"
